Rails.application.routes.draw do

  #assessment/survey
  get 'talent_accelerator/assessment/survey/page_1' => "custom/talent_accelerator/assessment/survey#page_1"
  get 'talent_accelerator/assessment/survey/page_2' => "custom/talent_accelerator/assessment/survey#page_2"
  get 'talent_accelerator/assessment/survey/page_3' => "custom/talent_accelerator/assessment/survey#page_3"
  get 'talent_accelerator/assessment/survey/page_4' => "custom/talent_accelerator/assessment/survey#page_4"
  get 'talent_accelerator/assessment/survey/page_5' => "custom/talent_accelerator/assessment/survey#page_5"
  get 'talent_accelerator/assessment/survey/page_6' => "custom/talent_accelerator/assessment/survey#page_6"
  get 'talent_accelerator/assessment/survey/page_7' => "custom/talent_accelerator/assessment/survey#page_7"
  get 'talent_accelerator/assessment/survey/page_8' => "custom/talent_accelerator/assessment/survey#page_8"
  get 'talent_accelerator/assessment/survey/page_9' => "custom/talent_accelerator/assessment/survey#page_9"
  get 'talent_accelerator/assessment/survey/page_10' => "custom/talent_accelerator/assessment/survey#page_10"
  get 'talent_accelerator/assessment/survey/page_11' => "custom/talent_accelerator/assessment/survey#page_11"
  get 'talent_accelerator/assessment/survey/page_12' => "custom/talent_accelerator/assessment/survey#page_12"
  get 'talent_accelerator/assessment/survey/page_13' => "custom/talent_accelerator/assessment/survey#page_13"
  get 'talent_accelerator/assessment/survey/page_14' => "custom/talent_accelerator/assessment/survey#page_14"
  get 'talent_accelerator/assessment/survey/page_15' => "custom/talent_accelerator/assessment/survey#page_15"
  get 'talent_accelerator/assessment/survey/page_16' => "custom/talent_accelerator/assessment/survey#page_16"
  get 'talent_accelerator/assessment/survey/page_17' => "custom/talent_accelerator/assessment/survey#page_17"
  get 'talent_accelerator/assessment/survey/page_18' => "custom/talent_accelerator/assessment/survey#page_18"
  get 'talent_accelerator/assessment/survey/page_19' => "custom/talent_accelerator/assessment/survey#page_19"
  get 'talent_accelerator/assessment/survey/page_20' => "custom/talent_accelerator/assessment/survey#page_20"
  get 'talent_accelerator/assessment/survey/page_21' => "custom/talent_accelerator/assessment/survey#page_21"
  get 'talent_accelerator/assessment/survey/page_22' => "custom/talent_accelerator/assessment/survey#page_22"
  get 'talent_accelerator/assessment/survey/page_23' => "custom/talent_accelerator/assessment/survey#page_23"
  get 'talent_accelerator/assessment/survey/page_24' => "custom/talent_accelerator/assessment/survey#page_24"
  get 'talent_accelerator/assessment/survey/page_25' => "custom/talent_accelerator/assessment/survey#page_25"
  
end